### ISSUE TITLE
ERROR: org.graylog2.bootstrap.CmdLineTool

### ISSUE THREAD

**Issue by kkrautwald** [Graylog2/graylog-docker#119]
Hello

After a long time of no problem, a restart causes this problem with Graylog server, that won't start up.

Anyone?

2020-05-19 11:58:28,830 ERROR: org.graylog2.bootstrap.CmdLineTool - Invalid configuration
com.github.joschi.jadconfig.ParameterException: Couldn't convert value for parameter "root_timezone"
at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:141) ~[graylog.jar:?]
at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:178) [graylog.jar:?]
at org.graylog2.bootstrap.Main.main(Main.java:50) [graylog.jar:?]
Caused by: com.github.joschi.jadconfig.ParameterException: Couldn't convert value "UTC +2" to DateTimeZone.
at com.github.joschi.jadconfig.jodatime.converters.DateTimeZoneConverter.convertFrom(DateTimeZoneConverter.java:26) ~[graylog.jar:?]
atccom.github.joschi.jadconfig.jodatime.converters.DateTimeZoneConverter.convertFrom(DateTimeZoneConverter.java:12) ~[graylog.jar:?]
at com.github.joschi.jadconfig.JadConfig.convertStringValue(JadConfig.java:167) ~[graylog.jar:?]
at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:139) ~[graylog.jar:?]

**Comment by kroepke** [comment]
@kkrautwald To properly understand this:
Have you changed the configuration in the meantime?
What is the actual value of `root_timezone` and where is it set? In the configuration file or as an environment variable?

Please note that `UTC +2` contains whitespace and that probably never parsed correctly, from a quick look the code that does the parsing shouldn't have significantly changed.

**Comment by kkrautwald** [comment]
Hello 

> Have you changed the configuration in the meantime?

No! 

> What is the actual value of `root_timezone` and where is it set? In the configuration file or as an environment variable?
I have not changed the server.conf, but only via environment variables. In my env.file I have 

GRAYLOG_TIMEZONE=Europe/Copenhagen

That is it... regarding time.
 
> Please note that `UTC +2` contains whitespace and that probably never parsed correctly, from a quick look the code that does the parsing shouldn't have significantly changed.

**Comment by mpfz0r** [comment]
> GRAYLOG_TIMEZONE=Europe/Copenhagen

Hi,
this variable should have zero effect. It's an ancient setting. 
However, if you use `GRAYLOG_ROOT_TIMEZONE` this should override your broken config and things should start working again.
