### ISSUE TITLE
Exception in monitor thread while connecting to server mongo

### ISSUE THREAD

**Issue by naisanza** [Graylog2/graylog-docker#16]
I just started the docker image, and it didn't connect to my exposed port 9000, and after I checked the logs, I saw the errors.

Environment:
```
Rancher v1.6.14
Kubernetes
```

Error Logs:
```
2/26/2018 2:41:54 AM2018-02-26 07:41:54,041 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
2/26/2018 2:41:54 AMcom.mongodb.MongoSocketException: mongo
2/26/2018 2:41:54 AM	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[graylog.jar:?]
2/26/2018 2:41:54 AM	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59) ~[graylog.jar:?]
2/26/2018 2:41:54 AM	at com.mongodb.connection.SocketStream.open(SocketStream.java:57) ~[graylog.jar:?]
2/26/2018 2:41:54 AM	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:107) ~[graylog.jar:?]
2/26/2018 2:41:54 AM	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:111) [graylog.jar:?]
2/26/2018 2:41:54 AM	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2/26/2018 2:41:54 AMCaused by: java.net.UnknownHostException: mongo
2/26/2018 2:41:54 AM	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_151]
2/26/2018 2:41:54 AM	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_151]
2/26/2018 2:41:54 AM	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_151]
2/26/2018 2:41:54 AM	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[?:1.8.0_151]
2/26/2018 2:41:54 AM	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[graylog.jar:?]
2/26/2018 2:41:54 AM	... 5 more
```

**Comment by naisanza** [comment]
Nevermind, I was expecting this to be a self-containing docker image. I saw it needed mongo and elasticsearch, additionally

**Comment by RaviGithub555** [comment]
Hi Naisanza,
I am trying to add multiple host and port in mongo uri like 
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
 if we given both correct host : port then this connecting to both host:port, mean two connection open with two host:port,

And if we configured 1 wrong host:post and one correct host:port, then its connecting with correct host:port but parallel giving below issue:


      main] org.mongodb.driver.cluster               : Adding discovered server 192.168.229.134:57019 to client view of cluster
2019-11-14 20:54:12.686  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.691  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.693  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class java.time.Instant as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.693  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.Instant to class java.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.936  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.937  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.938  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.LocalDateTime to class java.time.Instant as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:12.938  WARN 13512 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from class java.time.Instant to class java.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might wanna check you annotation setup at the converter implementation.
2019-11-14 20:54:13.863  INFO 13512 --- [8.229.134:57019] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1}] to 192.168.229.134:57019
2019-11-14 20:54:13.940  INFO 13512 --- [           main] .s.s.UserDetailsServiceAutoConfiguration : 

52.161.85:27018] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server 10.252.161.85:27018

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:67) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.8.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method) ~[na:na]
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64) ~[mongodb-driver-core-3.8.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:62) ~[mongodb-driver-core-3.8.2.jar:na]
	... 3 common frames omitted

Can you anybody please help me  here , that once it connected with one host:port it should not monitor with other host:port,

**Comment by ainiml** [comment]
Hey @RaviGithub555 

@naisanza here. Sorry I can't be of much help, but I never finished getting it up and running

**Comment by anjagarwal** [comment]
> Nevermind, I was expecting this to be a self-containing docker image. I saw it needed mongo and elasticsearch, additionally

How have you resolved this?
