### ISSUE TITLE
Content packs not auto loading steams

### ISSUE THREAD

**Issue by tobias-g** [Graylog2/graylog-docker#32]
I'm trying to auto load streams as content packs with auto load but they are not appearing. It does add them in the UI `/system/contentpacks` but I have to manually apply them.

Graylog version v2.4.6+ceaa7e4

```
docker create --link mongo \
    -p 9000:9000 -p 12201:12201 -p 514:514 -p 5555:5555 \
    --name graylog \
    -e GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true \
    -e GRAYLOG_CONTENT_PACKS_AUTO_LOAD=tcp-input.json,my-stream.json \
    -e GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks \
    ... other env values ...
    graylog/graylog:2.4
```

Wondering if this is an issue or something I've misconfigured.

**Comment by mariussturm** [comment]
Hi,
in general that should work. Do you see any error in the server logs related to content pack loading?

**Comment by tobias-g** [comment]
See the following when I look for content pack related stuff in graylog logs.

```
2018-08-07 13:52:26,037 ERROR: org.graylog2.bundles.BundleImporter - Error while creating entities in content pack. Starting rollback.
java.lang.IllegalStateException: No default index set configured. This is a bug!
    at com.google.common.base.Preconditions.checkState(Preconditions.java:459) ~[graylog.jar:?]
    at org.graylog2.indexer.indexset.MongoIndexSetService.getDefault(MongoIndexSetService.java:105) ~[graylog.jar:?]
    at org.graylog2.indexer.MongoIndexSetRegistry.getDefault(MongoIndexSetRegistry.java:145) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleImporter.createStream(BundleImporter.java:573) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleImporter.createStreams(BundleImporter.java:557) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleImporter.runImport(BundleImporter.java:189) [graylog.jar:?]
    at org.graylog2.bundles.BundleService.applyConfigurationBundle(BundleService.java:112) [graylog.jar:?]
    at org.graylog2.periodical.ContentPackLoaderPeriodical.doRun(ContentPackLoaderPeriodical.java:196) [graylog.jar:?]
    at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
2018-08-07 13:52:26,085 INFO : org.graylog2.inputs.InputStateListener - Input [Syslog TCP/5b69a4194cedfd0001f3c24d] is now STARTING
2018-08-07 13:52:26,067 ERROR: org.graylog2.periodical.ContentPackLoaderPeriodical - Uncaught exception in periodical
java.lang.RuntimeException: java.lang.IllegalStateException: No default index set configured. This is a bug!
    at org.graylog2.bundles.BundleImporter.runImport(BundleImporter.java:200) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleService.applyConfigurationBundle(BundleService.java:112) ~[graylog.jar:?]
    at org.graylog2.periodical.ContentPackLoaderPeriodical.doRun(ContentPackLoaderPeriodical.java:196) ~[graylog.jar:?]
    at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalStateException: No default index set configured. This is a bug!
    at com.google.common.base.Preconditions.checkState(Preconditions.java:459) ~[graylog.jar:?]
    at org.graylog2.indexer.indexset.MongoIndexSetService.getDefault(MongoIndexSetService.java:105) ~[graylog.jar:?]
    at org.graylog2.indexer.MongoIndexSetRegistry.getDefault(MongoIndexSetRegistry.java:145) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleImporter.createStream(BundleImporter.java:573) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleImporter.createStreams(BundleImporter.java:557) ~[graylog.jar:?]
    at org.graylog2.bundles.BundleImporter.runImport(BundleImporter.java:189) ~[graylog.jar:?]
    ... 4 more
```

Not sure what to make of it to be honest, hopefully makes more sense to someone else.

**Comment by mariussturm** [comment]
The default index set in Elasticsearch that is created during first start-up is not there. Maybe your ES cluster is in an error state or not accessible at all?

**Comment by tobias-g** [comment]
Running the following locally gets me this scenario:

```
docker run --name mongo -d mongo:3

docker run --name elasticsearch \
    -e "http.host=0.0.0.0" \
    -e "xpack.security.enabled=false" \
    -d docker.elastic.co/elasticsearch/elasticsearch:5.6.2

docker create --link mongo --link elasticsearch \
    -p 9000:9000 -p 12201:12201 -p 514:514 -p 5555:5555 \
    --name graylog \
    -e GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true \
    -e GRAYLOG_CONTENT_PACKS_AUTO_LOAD=input.json,streams.json \
    -e GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks \
    -e GRAYLOG_WEB_ENDPOINT_URI="http://127.0.0.1:9000/api" \
    graylog/graylog:2.4

docker cp /tmp/contentpacks/. graylog:/usr/share/graylog/data/contentpacks/

docker start graylog
```
Elastic search doesn't seem to be in an error state as far as I can tell.

Not used elastic search too much so is this a case of needing to wait a bit for elastic search to start and settle itself or do I need to set something up in elastic search before I start graylog to get the default index set?

GrayLog does eventually start up and work as expected so it's either fixing this issue itself of waiting until that index is there?

**Comment by mariussturm** [comment]
That's possible, there shout be a log message about it later in the file. Usually you expose the data directory of the ES container anyways to keep state of the system. If you let it create once the import of the content pack should work then.

**Comment by tobias-g** [comment]
Yep looks like that was it 👍 

Started elastic search and followed the logs unitl I saw
```
[2018-08-07T14:37:25,519][INFO ][o.e.c.m.MetaDataCreateIndexService] [XZjuckQ] [.triggered_watches] creating index, cause [auto(bulk api)], templates [triggered_watches], shards [1]/[1], mappings [triggered_watch]
```

And started graylog after that, streams and inputs all accounted for and present after that.

Also as far as exposing the data directory in ES using AWS ES anyway the above was just a local example.

Thanks for the help here :)

**Comment by j4r3kb** [comment]
I have the same issue but when using docker-compose.yml
Here is my stack:
```
  mongo:
    image: mongo:4.2
    restart: on-failure:3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    env_file: .env_elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    restart: on-failure:3

  graylog:
    image: graylog/graylog:4.0
    env_file: .env_graylog
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9999:9000
      - 12201:12201/udp
      - 12401:12401/udp
    restart: on-failure:3
    volumes:
      - ./graylog/contentpacks:/usr/share/graylog/data/contentpacks
```

content packs are linked with volume, the .env_graylog file contents are:

```
GRAYLOG_CONTENT_PACKS_AUTO_INSTALL=nginx.json
GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks
GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
```

When I log into graylog's panel I only see the nginx pack in the list of available packeges, but need to install it by clicking the button.
As you can see I have added `depends_on` to the yaml so graylog should start after mongo and elastic.
What else should I do?
